// Les cinq biomes. Chacun change le pouls, la palette, la pression de la Cendre
// et introduit une règle qui lui est propre.

export const BIOMES = {
  clairiere: {
    id: 'clairiere',
    name: 'La Clairière Murmurante',
    short: 'Clairière',
    bpm: 96,
    cols: 9, rows: 7,
    cost: 0,
    blightMult: 0.75,
    growthMult: 1.15,
    fissures: 2,
    transpose: 0,
    rule: 'Sol tendre. La Cendre y avance lentement. Un bon endroit pour apprendre à écouter.',
    palette: {
      sky: ['#2f4f43', '#1c3129'],
      ground: '#3f5c4a',
      groundAlt: '#456450',
      soil: '#6b5138',
      water: '#3d7a8c',
      accent: '#8fce6a',
      fog: 'rgba(180,220,170,0.06)',
    },
    ambience: { pad: 'bois', bird: true, water: 0.15, wind: 0.35 },
  },
  marais: {
    id: 'marais',
    name: 'Les Marais de Verre',
    short: 'Marais',
    bpm: 84,
    cols: 9, rows: 7,
    cost: 1500,
    blightMult: 1.0,
    growthMult: 1.0,
    fissures: 3,
    transpose: 3,
    rule: 'La marée monte et descend. Les cases submergées transposent tes notes d’une tierce.',
    palette: {
      sky: ['#28394f', '#16202e'],
      ground: '#3a5265',
      groundAlt: '#41596d',
      soil: '#5a5a48',
      water: '#5aa7c4',
      accent: '#4fc3b1',
      fog: 'rgba(160,210,230,0.08)',
    },
    ambience: { pad: 'verre', bird: false, water: 0.6, wind: 0.2 },
    tide: true,
  },
  vallee: {
    id: 'vallee',
    name: 'La Vallée Calcinée',
    short: 'Vallée',
    bpm: 120,
    cols: 10, rows: 7,
    cost: 4000,
    blightMult: 1.45,
    growthMult: 0.95,
    fissures: 5,
    transpose: -2,
    rule: 'La sécheresse boit ton eau. La Cendre est native ici : elle ne dort jamais.',
    palette: {
      sky: ['#4a2f2a', '#2a1a17'],
      ground: '#6b4636',
      groundAlt: '#7a513d',
      soil: '#8a5c3e',
      water: '#5d8f8a',
      accent: '#f0a24a',
      fog: 'rgba(255,170,110,0.07)',
    },
    ambience: { pad: 'braise', bird: false, water: 0.05, wind: 0.55 },
    drought: 2.1,
  },
  canopee: {
    id: 'canopee',
    name: 'La Canopée Suspendue',
    short: 'Canopée',
    bpm: 108,
    cols: 10, rows: 7,
    cost: 8000,
    blightMult: 1.2,
    growthMult: 1.05,
    fissures: 4,
    transpose: 5,
    rule: 'Le sol est fait d’îlots. Le vent déplace les graines fraîchement semées.',
    palette: {
      sky: ['#243d55', '#152534'],
      ground: '#3d6154',
      groundAlt: '#447060',
      soil: '#6d5b3a',
      water: '#4d93a8',
      accent: '#7c8ce0',
      fog: 'rgba(190,215,255,0.07)',
    },
    ambience: { pad: 'souffle', bird: true, water: 0.1, wind: 0.8 },
    voids: 0.16,
    wind: true,
  },
  coeur: {
    id: 'coeur',
    name: 'Le Cœur Sourd',
    short: 'Cœur',
    bpm: 132,
    cols: 9, rows: 7,
    cost: 15000,
    blightMult: 1.8,
    growthMult: 1.0,
    fissures: 6,
    transpose: 0,
    rule: 'La source du silence. La musique s’y éteint par vagues : joue de mémoire.',
    palette: {
      sky: ['#31303a', '#16151c'],
      ground: '#43414d',
      groundAlt: '#4b4956',
      soil: '#5b5450',
      water: '#6a7f92',
      accent: '#e8dcc6',
      fog: 'rgba(230,225,215,0.05)',
    },
    ambience: { pad: 'sourd', bird: false, water: 0.0, wind: 0.45 },
    silence: true,
  },
};

export const BIOME_ORDER = ['clairiere', 'marais', 'vallee', 'canopee', 'coeur'];

export function getBiome(id) { return BIOMES[id] || BIOMES.clairiere; }
