#!/usr/bin/env python3
"""Génère assets/sprites/ui/icons.png : petites icônes 16 × 16 de l'interface, dessinées pour le jeu
dans la palette des packs Kenney (Tiny Farm / UI Pack Pixel Adventure). Placées sous CC0.

Ligne 0 : météo    — sunny, cloudy, rain, storm, heatwave, snow
Ligne 1 : saisons  — spring, summer, autumn, winter ; puis star, star-empty
Ligne 2 : contrôle — pause, play, fast, faster, menu, close, sound, mute
Ligne 3 : divers   — coin, bill, calendar, lock, water, harvest, seed, info

Et assets/sprites/ui/favicon.png (carotte mûre de Tiny Farm, agrandie ×4).
Usage : python3 assets/sprites/ui/generate-icons.py (depuis la racine du dépôt).
"""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent

PAL = {
    '.': None,
    'K': (63, 38, 49),      # contour Kenney
    'W': (255, 255, 255),
    'w': (255, 241, 210),   # parchemin
    'C': (223, 231, 239),   # nuage clair
    'G': (169, 184, 198),   # nuage ombre
    'S': (119, 141, 159),   # ardoise claire
    's': (81, 95, 107),     # ardoise sombre
    'd': (100, 118, 133),   # ardoise
    'Y': (253, 220, 0),     # jaune
    'O': (255, 182, 0),     # orange doré
    'D': (181, 131, 0),     # jaune sombre
    'B': (99, 175, 243),    # bleu pluie
    'b': (59, 104, 145),    # bleu sombre
    'L': (191, 227, 255),   # bleu glace
    'R': (226, 102, 91),    # rouge
    'r': (142, 63, 56),     # rouge sombre
    'P': (244, 160, 186),   # rose
    'p': (206, 104, 140),   # rose sombre
    'V': (124, 201, 85),    # vert clair
    'v': (82, 135, 56),     # vert sombre
    'A': (231, 138, 54),    # orange automne
    'a': (178, 88, 38),     # brun-orange
    'N': (197, 135, 71),    # bois clair
    'n': (163, 112, 58),    # bois
    'M': (109, 75, 39),     # bois sombre
}

ICONS = {}

ICONS['sunny'] = """
................
.......KK.......
.......YK.......
..KK...YK...KK..
..KYK......KYK..
....KKKKKKKK....
...KYYYYYYYOK...
...KYWWYYYYOK...
KYYKYWYYYYYOKYYK
KKK.KYYYYYYOKKK.
...KYYYYYYOOK...
...KOOOOOOOOK...
..KYKKKKKKKKYK..
..KK...YK...KK..
.......YK.......
.......KK.......
"""

ICONS['cloudy'] = """
................
.........KK.K...
.....KK.KYYK....
....KYKKYYYOKK..
......KKKKYYOK..
.....KWWWWKYOK..
..KKKWWWWWWKKK..
.KWWWWWWWWWWWK..
KWWWWWWWWWWWWWK.
KWWWWWWWWWWWWCWK
KCWWWWWWWWWWCCWK
KCCWWWWWWWWCCCCK
.KGCCCCCCCCCCGK.
..KKKKKKKKKKKK..
................
................
"""

ICONS['rain'] = """
................
.....KKKK.......
....KCCCCKKKK...
..KKCCCCCCCCCK..
.KCCCCCCCCCCCCK.
KCCCCCCCCCCCCCGK
KGCCCCCCCCCCCGGK
KGGGGGGGGGGGGGGK
.KKKKKKKKKKKKKK.
................
..KB...KB...KB..
..KB...KB...KB..
.KB...KB...KB...
.KB...KB...KB...
................
................
"""

ICONS['storm'] = """
................
.....KKKK.......
....KSSSSKKKK...
..KKSSSSSSSSSK..
.KSSSSSSSSSSSSK.
KSSSSSSSSSSSSSdK
KdSSSSSSSKKSSddK
KddddddKKYKddddK
.KKKKKKKYYKKKKK.
......KYYKKKK...
.KB..KYYYYYYK...
.KB..KKKKYYK..B.
KB......KYK..KB.
KB.....KYK...KB.
.......KK.......
................
"""

ICONS['heatwave'] = """
.....K.KK.K.....
...K.KOOOOK.K...
....KOYYYYYAK...
.K.KOYWYYYYYAK.K
..KOYWYYYYYYYAK.
..KOYYYYYYYYYAK.
..KOYYYYYYYYYAK.
.K.KAOYYYYYAAK.K
....KAAOOOAAK...
...K.KKKKKKK.K..
................
................
................
................
................
................
"""

ICONS['snow'] = """
................
.....KKKK.......
....KCCCCKKKK...
..KKCCCCCCCCCK..
.KCCCCCCCCCCCCK.
KCCCCCCCCCCCCCGK
KGCCCCCCCCCCCGGK
KGGGGGGGGGGGGGGK
.KKKKKKKKKKKKKK.
...K.........K..
..KWK.......KWK.
.KWLWK..K..KWLWK
..KWK..KWK..KWK.
...K..KWLWK..K..
.......KWK......
........K.......
"""

ICONS['spring'] = """
................
......KKK.......
.....KPPPK......
..KKKPWPPKKKK...
.KPPPKPPKPPPPK..
.KPPPPKKKPPPpK..
..KPPPKYKPPpK...
...KKKYOYKKK....
..KPPPKYKPPPK...
.KPPPpKKKPPPpK..
.KPppKPPPKpppK..
..KKKKPPpKKKK...
.....KKpKKv.....
..KvK..KvvK.....
..KvvK.KvK......
...KKKKKK.......
"""

ICONS['summer'] = """
................
.....K.KK.K.....
....KYKYYKYK....
..K.KYYYYYYK.K..
.KYKKYYYYYYKKYK.
..KYYKKKKKKYYK..
.KYYKaaaaaaKYYK.
KYYYKaMaaMaKYYYK
.KYYKaaaaaaKYYK.
..KYYKaMMaKYYK..
.KYKKKKKKKKKKYK.
..K.KYYKKYYK.K..
....KYKvvKYK....
.....K.Kv.K.....
....KvvKvKvK....
.....KKKvKK.....
"""

ICONS['autumn'] = """
................
.......KK.......
......KAAK......
..KK..KAAK..KK..
..KAKKAAAAKKAK..
..KAAAAAAAAAAK..
.KKAAAAaAAAAAKK.
KAAAAAAaAAAAAAAK
.KAAAAaAaAAAAAK.
..KAAAAaAAAAAK..
..KKAaAaAaAKKK..
...KAAAaAAAK....
..KAAKKaKKAAK...
..KKK.KaK.KKK...
.......aK.......
.......KK.......
"""

ICONS['winter'] = """
................
.......KK.......
....KK.KLK.KK...
....KLKKLKKLK...
.....KLKLKLK....
..KKKKKLLLKKKKK.
..KLLLLLWLLLLLK.
..KKKKKLLLKKKKK.
.....KLKLKLK....
....KLKKLKKLK...
....KK.KLK.KK...
.......KK.......
................
................
................
................
"""

ICONS['star'] = """
................
.......KK.......
......KYYK......
......KYYK......
.....KYWYYK.....
KKKKKKYWYYKKKKKK
KOYYYYYYYYYYYYOK
.KOYYYYYYYYYYOK.
..KOYYYYYYYYOK..
...KOYYYYYYOK...
...KOYYYYYYOK...
..KOYYYOOYYYOK..
..KOYYOKKOYYOK..
.KOYOKK..KKOYOK.
.KOOK......KOOK.
.KKK........KKK.
"""

ICONS['star-empty'] = """
................
.......KK.......
......KssK......
......KssK......
.....KssssK.....
KKKKKKssssKKKKKK
KsddddddddddddsK
.KsddddddddddsK.
..KsddddddddsK..
...KsddddddsK...
...KsddddddsK...
..KsdddssdddsK..
..KsddsKKsddsK..
.KsdsKK..KKsdsK.
.KssK......KssK.
.KKK........KKK.
"""

ICONS['pause'] = """
................
................
................
...KKKK..KKKK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KwwK..KwwK...
...KKKK..KKKK...
................
................
................
"""

ICONS['play'] = """
................
................
................
.....KK.........
.....KwKK.......
.....KwwwKK.....
.....KwwwwwKK...
.....KwwwwwwwK..
.....KwwwwwwwK..
.....KwwwwwKK...
.....KwwwKK.....
.....KwKK.......
.....KK.........
................
................
................
"""

ICONS['fast'] = """
................
................
................
..KK.....KK.....
..KwKK...KwKK...
..KwwwKK.KwwwKK.
..KwwwwwKKwwwwwK
..KwwwwwwKwwwwwK
..KwwwwwwKwwwwwK
..KwwwwwKKwwwwwK
..KwwwKK.KwwwKK.
..KwKK...KwKK...
..KK.....KK.....
................
................
................
"""

ICONS['faster'] = """
................
................
................
KK...KK...KK....
KwK..KwK..KwK...
KwwK.KwwK.KwwK..
KwwwKKwwwKKwwwK.
KwwwwKwwwwKwwwwK
KwwwwKwwwwKwwwwK
KwwwKKwwwKKwwwK.
KwwK.KwwK.KwwK..
KwK..KwK..KwK...
KK...KK...KK....
................
................
................
"""

ICONS['menu'] = """
................
................
................
..KKKKKKKKKKKK..
..KwwwwwwwwwwK..
..KKKKKKKKKKKK..
................
..KKKKKKKKKKKK..
..KwwwwwwwwwwK..
..KKKKKKKKKKKK..
................
..KKKKKKKKKKKK..
..KwwwwwwwwwwK..
..KKKKKKKKKKKK..
................
................
"""

ICONS['close'] = """
................
................
................
...KK......KK...
...KwK....KwK...
....KwK..KwK....
.....KwKKwK.....
......KwwK......
......KwwK......
.....KwKKwK.....
....KwK..KwK....
...KwK....KwK...
...KK......KK...
................
................
................
"""

ICONS['sound'] = """
................
................
......KK....K...
.....KwK.....K..
....KwwK..K...K.
.KKKwwwK...K..K.
.KwwwwwK...K..K.
.KwwwwwK...K..K.
.KwwwwwK...K..K.
.KKKwwwK...K..K.
....KwwK..K...K.
.....KwK.....K..
......KK....K...
................
................
................
"""

ICONS['mute'] = """
................
................
......KK........
.....KwK........
....KwwK........
.KKKwwwK.K...K..
.KwwwwwK..K.K...
.KwwwwwK...K....
.KwwwwwK..K.K...
.KKKwwwK.K...K..
....KwwK........
.....KwK........
......KK........
................
................
................
"""

ICONS['coin'] = """
................
................
.....KKKKKK.....
....KYYYYYOK....
...KYWYYYYYOK...
..KYWYKKKKYYOK..
..KYYKYYYOKYOK..
..KYYKYYYOKYOK..
..KYYKYYYOKYOK..
..KYYKYOOOKYOK..
..KOYYKKKKYOOK..
...KOYYYYYOOK...
....KOOOOOOK....
.....KKKKKK.....
................
................
"""

ICONS['bill'] = """
................
..KKKKKKKKKK....
..KwwwwwwwwKK...
..KwKKKKKwwKwK..
..KwwwwwwwwKKKK.
..KwKKKKKKwwwwK.
..KwwwwwwwwwwwK.
..KwKKKKKKKwwwK.
..KwwwwwwwwwwwK.
..KwKKKKwwwwwwK.
..KwwwwwwwKKKwK.
..KwwwwwwKRRRKK.
..KwwwwwwKRRRK..
..KKKKKKKKKKKK..
................
................
"""

ICONS['calendar'] = """
................
....KK....KK....
..KKKKKKKKKKKK..
..KRRRRRRRRRRK..
..KRRKRRRRKRRK..
..KKKKKKKKKKKK..
..KwwwwwwwwwwK..
..KwKKwKKwKKwK..
..KwwwwwwwwwwK..
..KwKKwKKwKKwK..
..KwwwwwwwwwwK..
..KwKKwKKwwwwK..
..KwwwwwwwwwwK..
..KKKKKKKKKKKK..
................
................
"""

ICONS['lock'] = """
................
................
......KKKK......
.....KSSSSK.....
....KSK..KSK....
....KSK..KSK....
....KSK..KSK....
...KKKKKKKKKK...
...KYYYYYYYYK...
...KYYYKKYYOK...
...KYYYKKYYOK...
...KYYYYKYYOK...
...KOYYYYYOOK...
...KOOOOOOOOK...
...KKKKKKKKKK...
................
"""

ICONS['water'] = """
................
.......KK.......
......KBBK......
......KBBK......
.....KBBBBK.....
.....KBBBBK.....
....KBBBBBBK....
....KBWBBBBK....
...KBWBBBBBbK...
...KBWBBBBBbK...
...KBBBBBBBbK...
...KBBBBBBbbK...
....KBBBBbbK....
.....KKKKKK.....
................
................
"""

ICONS['harvest'] = """
................
.........KK.....
........KvvK....
......KKVvK.....
.....KVVvKKK....
.....KKvKVVK....
....KAAKKvVK....
...KAAAAKKK.....
...KAWAAAK......
..KAAWAAAK......
..KAAAAAaK......
..KAAAAAaK......
...KAAAaK.......
...KAAaK........
....KKK.........
................
"""

ICONS['seed'] = """
................
................
.....KKKKKK.....
....KwwKKwwK....
....KKwwwwKK....
....KNNNNNNK....
...KNNNNNNNNK...
...KNNNVVNNNK...
..KNNNVvvVNNNK..
..KNNNNVvNNNNK..
..KNNNNvNNNNnK..
..KnNNNNNNNnnK..
...KnnnnnnnnK...
....KKKKKKKK....
................
................
"""

ICONS['info'] = """
................
.....KKKKKK.....
....KBBBBBBK....
...KBBBWWBBBK...
..KBBBBWWBBBBK..
..KBBBBBBBBBBK..
..KBBBWWWBBBBK..
..KBBBBWWBBBBK..
..KBBBBWWBBBBK..
..KBBBBWWBBBBK..
..KBBBWWWWBBbK..
...KBBBBBBBbK...
....KbbbbbbK....
.....KKKKKK.....
................
................
"""

ROWS = [
    ['sunny', 'cloudy', 'rain', 'storm', 'heatwave', 'snow'],
    ['spring', 'summer', 'autumn', 'winter', 'star', 'star-empty'],
    ['pause', 'play', 'fast', 'faster', 'menu', 'close', 'sound', 'mute'],
    ['coin', 'bill', 'calendar', 'lock', 'water', 'harvest', 'seed', 'info'],
]


def parse(name):
    lines = [l for l in ICONS[name].strip('\n').split('\n')]
    assert len(lines) == 16, f'{name}: {len(lines)} lignes'
    for i, l in enumerate(lines):
        assert len(l) == 16, f'{name} ligne {i}: {len(l)} colonnes « {l} »'
        for ch in l:
            assert ch in PAL, f'{name}: couleur inconnue {ch!r}'
    return lines


def heat_waves(sheet, ox, oy):
    """Deux ondes de chaleur (sinusoïdes rouges, ombrées) sous le soleil de la canicule."""
    import math
    for base, color in ((11, 'R'), (14, 'r')):
        for x in range(1, 15):
            y = base + round(math.sin(x * 2 * math.pi / 8))
            sheet.putpixel((ox + x, oy + y), PAL[color] + (255,))


def main():
    cols = max(len(r) for r in ROWS)
    sheet = Image.new('RGBA', (cols * 16, len(ROWS) * 16), (0, 0, 0, 0))
    for ry, row in enumerate(ROWS):
        for cx, name in enumerate(row):
            for y, line in enumerate(parse(name)):
                for x, ch in enumerate(line):
                    c = PAL[ch]
                    if c:
                        sheet.putpixel((cx * 16 + x, ry * 16 + y), c + (255,))
            if name == 'heatwave':
                heat_waves(sheet, cx * 16, ry * 16)
    sheet.save(HERE / 'icons.png')

    farm = Image.open(ROOT / 'assets/sprites/tiny-farm.png').convert('RGBA')
    carrot = farm.crop((6 * 16, 0, 7 * 16, 16))  # carotte mûre (col 6, ligne 0)
    carrot.resize((64, 64), Image.NEAREST).save(HERE / 'favicon.png')
    print('icons.png et favicon.png générés')


if __name__ == '__main__':
    main()
